### ISSUE TITLE
How to scaffold a component in the test iframe?

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-angular-unit-test#1]
The `mount` function exposed by this package should mount the given component under test in the iframe's window. For example, here is the same code from https://github.com/bahmutov/cypress-angularjs-unit-test

```js
export const mount = function (template, modules = []) {
  if (arguments.length === 1) {
    // test did not pass a template, just list of modules
    modules = template
    template = ''
  }

  // must inject into a "div" and not into "document" directly,
  // Angular.js goes up to "html" parent element
  // and stores its state there, affecting every test afterwards
  const html = `
    <head>
      <meta charset="UTF-8">
    </head>
    <body>
      <div id="app">
        ${template}
      </div>
    </body>
  `

  const document = cy.state('document')
  document.write(html)
  document.close()

  cy.window().then(w => {
    w.angular = angular
    cy.log('Angular.js', w.angular.version.full)
    const el = document.getElementById('app')
    w.angular.bootstrap(el, modules)
  })
}
```

In this repo, I could not find how to scaffold Angular component on demand. See [cypress/integration/spec.ts](cypress/integration/spec.ts) currently. I am trying to put the component into the test iframe and start the app

```typescript
  beforeEach(() => {
    const html = `
      <head>
        <meta charset="UTF-8">
      </head>
      <body>
        <app-root></app-root>
      </body>
    `
    const document = (cy as any).state('document')
    document.write(html)
    document.close()

    cy.get('app-root').then(el$ => {
      platformBrowserDynamic()
        .bootstrapModule(AppModule)
        .then(function (moduleRef) {
          moduleRef.instance.app.bootstrap(AppComponent, el$.get(0))
        })
    })
  })

  it('works', () => {})
```

But so far - no luck.

## steps to reproduce

- Clone this repo
- `npm install`
- `npx cypress open` starts Cypress GUI
- click on `spec.ts` file and it will run the test

Attention @igorminar

**Comment by bahmutov** [comment]
Yeah, I am even thinking we need something like this https://glebbahmutov.com/blog/rolling-for-test/ to bundle component over and over and bootstrap it in the test iframe :(

**Comment by geocine** [comment]
we can also bootstrap it as a custom element using @angular/elements, if that makes sense

**Comment by meDavid** [comment]
https://github.com/angular/angular/issues/20229 might be related

**Comment by meDavid** [comment]
@bahmutov I have the rendering working for elements that use inline templates and styles. 

When using `templateUrl` and `styleUrls` instead of `template` and `styles` in the @Component decorator there specified urls (for app.component.html and app.component.css) need te be available on the server. Now the request url http://localhost:61601/__cypress/iframes/integration/app.component.html doesn't correctly resolve to /src/app/app.component.html. Another solution is to inline the template and style  resources using `ngc`.

**Comment by geocine** [comment]
@meDavid thanks for pointing that out, I did not notice. The PR #2 should be able to solve this issue

**Comment by meDavid** [comment]
@bahmutov Is there a way to make cypress look for the *.spec.ts files in the /src/** directories instead of the cypress/integration directory?

**Comment by pvdyck** [comment]
I am searching for a way to get code coverage of my cypress tests for an angular7 project and this solution should be working, I mean when it will be working.

Using the angular CLI, if I can mount the application within karma and launch my cypress tests in a spec.ts file, I should get a code coverage report of my e2e tests.

Anyone tried this approach ?

Thanks a lot

**Comment by tobiaseisenschenk** [comment]
Since you get the app to start, the problem is to add the respective component dynamically? I assume the dom stays empty because angular does not load the component. We should be able to use the [Dynamic Component Loader](https://angular.io/guide/dynamic-component-loader) to achieve that.

**Comment by kayvanbree** [comment]
@tobiaseisenschenk shouldn't you already have bootstrapped Angular before you can use that?

**Comment by kayvanbree** [comment]
I'm getting a lot of error messages like these:

```
E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
[tsl] ERROR in E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,47)
      TS1005: ';' expected.

E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
[tsl] ERROR in E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,90)
      TS1005: '(' expected.

E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
[tsl] ERROR in E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,104)
      TS1005: ']' expected.

E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
[tsl] ERROR in E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,112)
      TS1005: ',' expected.
```

Anybody know what I'm doing wrong?

**Comment by kayvanbree** [comment]
@geocine so it should work? If so, the readme should be updated.

**Comment by LeJeanbono** [comment]
Is it ok for you guys now with TestBed implementation ?

**Comment by LeJeanbono** [comment]
We are ok now, fell free to open an other issue if you have mount problem
