### ISSUE TITLE
Unit testing without UI

### ISSUE THREAD

**Issue by DonBrowny** [bahmutov/cypress-angular-unit-test#129]
Hi,
Is there a way to perform unit testing in angular apps without UI, ie., test specific components / services / directives. I am new to unit testing on JS frameworks, so a bit confused whether the mentioned UI unit test is the usual approach or testing individual components (like they do in jasmine and karma) is the general one

**Comment by blackorion** [comment]
you can check [Jest with Angular](https://itnext.io/how-to-use-jest-in-angular-aka-make-unit-testing-great-again-e4be2d2e92d1).

**Comment by LeJeanbono** [comment]
You can also use TestBed which is provided by Angular.
