### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module

### ISSUE THREAD

**Issue by lance-cfa** [bahmutov/cypress-angular-unit-test#130]
I've copied your cypress/integration/spec.ts file to my cypress/integration/ folder, but when I try to open (cypress open), I'm getting this error:

`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (4:0) while parsing /code/pricing-proj/pricing-ui/dev/pricing-portal-ui/cypress/integration/test-ng.ts while parsing file: /code/pricing-proj/pricing-ui/dev/pricing-portal-ui/cypress/integration/test-ng.ts`
 
I have my tsconfig.spec.json set to use module: "commonjs". 

tsconfig.json
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "skipLibCheck": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "baseUrl": "./",
    "module": "commonjs",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "baseUrl": "./node_modules",
    "paths": {
      "core-js/es7/reflect": [
        "../node_modules/core-js/proposals/reflect-metadata"
      ],
      "core-js/es6/*": ["../node_modules/core-js/es"],
      "core-js/es7/*": ["../node_modules/core-js/es"]
    }
  },
  "exclude": [
    "**/*.spec.ts",
    "./node_modules/*"
  ]

}`

tsconfig.spec.json
`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
`

Do you know what might be the issue?

**Comment by LeJeanbono** [comment]
Are you using Babel or Webpack ?

**Comment by LeJeanbono** [comment]
I close this one (no answer), feel free to test with the new version !
I'll reopen it if you need.
