### ISSUE TITLE
Does not work with components which has changeDetection: ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by MichaelBrimer** [bahmutov/cypress-angular-unit-test#148]
Hi
Great and very interesting work, I have used it with angular 9 with only one problem.
There are problems with components that has ChangeDetectionStrategy.OnPush.
I have played around with your code and even returned a componentRef.instance, where I set input and an app where I call tick.
I have tried different things, like componentRef.changeDetectorRef.markForCheck(); but can still not get it to work.
It might be because there is no view?
Do you have any idea how to fix this?
Thanks

**Comment by LeJeanbono** [comment]
Hi !
Can you provide us your component and the associated test case please ?

**Comment by MichaelBrimer** [comment]
Thanks for the fast reply
This is the most basic component and test I could think of:

import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
Component:

@Component({
  selector: 'cypress-unit-test',
  template: `{{ data }}`,
  changeDetection: ChangeDetectionStrategy.OnPush // It works fine without this line
})
export class CypressUnitTestComponent {
  @Input() data = '';
}

Test:
import { mount } from 'cypress-angular-unit-test/dist';
import { CypressUnitTestComponent } from './cypress-unit-test.component';

describe('Example of a cypress test of a component', () => {
  beforeEach(() => {});

  it('Test that data has changed on the DateRowComponent', () => {
    const data = 'It works';
    mount(CypressUnitTestComponent, { data });
    cy.contains(data);
  });
});

**Comment by LeJeanbono** [comment]
Hey @MichaelBrimer, make it work in #152 
Is it ok for you ?

**Comment by MichaelBrimer** [comment]
> Hey @MichaelBrimer, make it work in #152
> Is it ok for you ?


Hey
Thanks for your effort.
I have tried to take the code and run it on my machine. 
As far as I can see it is the same problem it works without OnPush. But not with OnPush.

**Comment by LeJeanbono** [comment]
Will provide a patch for this
See the Angular issue : https://github.com/angular/angular/issues/12313

**Comment by LeJeanbono** [comment]
Something like this should be fine :
```js
beforeEach(() => {
    setConfig({ detectChanges: false });
    initEnv(OnPushStratComponent);
  });

  it('mount work', () => {
    const data = 'It works onPush';
    const fixture = mount(OnPushStratComponent, { data });
    fixture.detectChanges();
    cy.contains(data);
  });
```
