### ISSUE TITLE
Cannot run all component tests

### ISSUE THREAD

**Issue by azaeng04** [bahmutov/cypress-angular-unit-test#151]
![2020-07-16_19h28_36](https://user-images.githubusercontent.com/13921692/87703071-8e07fa80-c79a-11ea-8eb0-dbcd709f699d.png)

**Comment by LeJeanbono** [comment]
Hi @azaeng04 ,
Can you provide us your component test ? Something we can reproduce ?
Which Angular version also.
Thanks

**Comment by azaeng04** [comment]
Hi @LeJeanbono 

Here is the repo where I pushed the code up to: https://gitlab.com/azaeng04/angular-test

Hopefully this helps.

**Comment by LeJeanbono** [comment]
I just push an Angular 9 example at https://github.com/bahmutov/cypress-angular-unit-test/tree/master/examples/ng9
Take a look and I will try your repo

**Comment by azaeng04** [comment]
Thanks @LeJeanbono I see your example only tests 1 component whereas the example I am sharing tests more than 1 component and I click the `Run All Spec` link on the Cypress runner

**Comment by azaeng04** [comment]
@LeJeanbono just running your example and I am not sure if you ran it, but I ran `nox cypress open` and clicked `Run all specs` and it only ran the integration tests. Also I noticed that you do have the experimentalComponentTests option enabled as well.

**Comment by LeJeanbono** [comment]
Ok got it !
It's more like a cypress problème/question, you can open an issue in their repository ( found nothing on that )
Maybe a new button is needed, dunno.
By the way, with `cypress run` all ( integration / component ) tests are executed

**Comment by azaeng04** [comment]
@LeJeanbono okay it is on the Cypress UI.

**Comment by LeJeanbono** [comment]
Fell free to open an issue in their repo !
