### ISSUE TITLE
Add Web Component (CUSTOM_ELEMENTS_SCHEMA) Support

### ISSUE THREAD

**Issue by IT521** [bahmutov/cypress-angular-unit-test#170]
Update initEnv to allow schemas to be passed in.

`initEnv(AppComponent, { schemas: [CUSTOM_ELEMENTS_SCHEMA] });`

<img width="1076" alt="Cypress Error" src="https://user-images.githubusercontent.com/2186633/94978326-e671ad00-04ea-11eb-99b5-fa5f9ab5234a.png">

**Comment by LeJeanbono** [comment]
Got something working with a simple custom element :) 
Can you give me your `aux-button` component please to make a concrete example ?

**Comment by IT521** [comment]
@LeJeanbono The changes you made in  #172 are exactly what I was looking for. Thanks!

**Comment by LeJeanbono** [comment]
Thanks for your report, hope you're enjoy the lib 🙂
