### ISSUE TITLE
No dist folder after installing v3.3.0

### ISSUE THREAD

**Issue by IT521** [bahmutov/cypress-angular-unit-test#173]
In `node_modules/cypress-angular-unit-test`:

README.md
package.json
support.js

<img width="1601" alt="Screen Shot 2020-10-04 at 10 57 15 AM" src="https://user-images.githubusercontent.com/2186633/95018913-73724e80-0630-11eb-90b8-d015cb2c5ff6.png">

**Comment by LeJeanbono** [comment]
Will take a look !

**Comment by LeJeanbono** [comment]
Sorry...
3.3.1 will fix that !
