### ISSUE TITLE
Styles not loading when mounting component

### ISSUE THREAD

**Issue by azaeng04** [bahmutov/cypress-angular-unit-test#177]
For some reason the scss styles won't load on mounting the component

The image on the right is what I am expecting, but I am getting the image on the left
![Screenshot from 2020-10-10 13-38-39](https://user-images.githubusercontent.com/13921692/95654189-a750e680-0afe-11eb-9a41-5d55933fd919.png)

**Comment by LeJeanbono** [comment]
Hmm a lot of code, can you provide me a example repo with the reproductible bug please ?
Thanks for your report @azaeng04 ;)

**Comment by azaeng04** [comment]
I wish that were a breeze to do. Do you think it might be related to the `assets` not loading. It is really a hard one cos I am trying to make use of Cypress on an app that makes full use of almost all angular features.

**Comment by LeJeanbono** [comment]
scss are not on your components ?

**Comment by azaeng04** [comment]
Yes it is

```
@Component({
    selector: "app-login",
    templateUrl: "./login.component.html",
    styleUrls: ["./login.component.scss"],
})
```

Also I did manage to reproduce this on your ng9 example and it does the same thing. That is also where I copied all dependencies. Best way would probably to do a video chat so you can see it for yourself.

**Comment by azaeng04** [comment]
Is there anything specific you would like to see?

**Comment by LeJeanbono** [comment]
Hard to say, you are loading a big component. Maybe a normal Cypress test is more appropriate for this testing case.
If you're using material, try to look at this example with the global css loading : https://github.com/bahmutov/cypress-angular-unit-test/tree/master/examples/ng9/src/app/material-button

**Comment by azaeng04** [comment]
Thanks I saw that example and I did that exact thing as per issue log #156 and it helped a bit, but all styles aren't loading still. 

![Screenshot from 2020-10-10 14-47-42](https://user-images.githubusercontent.com/13921692/95655439-9658a300-0b07-11eb-9bc4-72b66a3c006f.png)

You can see it styled some componentes, but not everything. We make use of PrimeNg for styling.

**Comment by azaeng04** [comment]
We also do make use

```
document.documentElement.style.setProperty(
      `--image-logo`,
      `url('assets/images/logo.png')`,
  );
```

To style some of those components, but they don't seem to be displaying and I do see it injecting those properties into the iframe where the app is being displayed.

**Comment by azaeng04** [comment]
I just discovered that this is because of the PrimeNg directives being used. This is why they are not being rendered correctly.

**Comment by azaeng04** [comment]
It doesn't load externally defined directives.

**Comment by LeJeanbono** [comment]
I made an example here https://github.com/bahmutov/cypress-angular-unit-test/tree/master/examples/ng9/src/app/primeng-button
It use component and directive of PrimeNG. You have to import the module where they are.

**Comment by azaeng04** [comment]
I see. Thanks. I managed to do that already. Is there a way for me to bundle up all the styles? Cos we have styles all over the place.
