### ISSUE TITLE
 "Mocha" has already been patched with "Zone" Error occurs when Async test with waitForAsync()

### ISSUE THREAD

**Issue by kishok** [bahmutov/cypress-angular-unit-test#181]
### Description

 I have add asynchronous unit test cases (e.g REST API calls) using angular **testBed** and  running the test suite with cypress test runner. It executes all test cases and passed for very first time without no Issues. On subsequent changes made to the spec file (or) Run all Tests again cause this issue

![image](https://user-images.githubusercontent.com/3517786/96748504-3c00f180-13e7-11eb-8b50-fba065a7aa25.png)

### Import file
`import 'zone.js/dist/zone-testing';` this dependency must be added to handle async methods via  **waitForAsync()** before all imports in spec.js file / in the cypress->support.js file.

### Support Needed
I know the message says it not related cypress but i don't know how to approach this problem in-terms of loading this dependency in test suite or the zone.js package itself have issues. Any Suggestions please from the community?

**Comment by LeJeanbono** [comment]
Hey @kishok thanks for your feedback !
Can you post your `ticketing-service` and the corresponding test please ?
Will try to make an example ;)

**Comment by kishok** [comment]
Hi @LeJeanbono,  i had shared [my repo](https://github.com/kishok/ticket-coupon) and Ticketing Service &  its spec file available under **src/app/shared** folder. Please look into the source code and run the unit Tests of ticketing service via **cypress open** to reproduce this issue.  Thanks for your support!

**Comment by LeJeanbono** [comment]
Got something working on your repo :

- Remove `import 'zone.js/dist/zone-testing';` from your test

- Remove `waitForAsync()` calls

- Add `Mocha.done` like this : 
```javascript
it('can barcode generated', (done) => {
    tktService.generateTicket(amt).then((resp: iTicketCoupon) => {
      assert.isNotNull(resp, 'Response is not NULL');
      assert.isObject(resp, 'Response is an Object');
      expect(resp.barcode, 'Response have the Barcode value').to.exist;
      assert.isNumber(resp.barcode, 'Barcode is Numeric');
      expect(resp.amount, 'Amount is equal').to.equal(amt);
      expect(resp, 'Response have all Barcode details').to.have.keys('barcode', 'amount', 'effectiveDate', 'status', 'location')
      barcodeVal = resp.barcode;
      done();
    });
  });
```
Produce :
![image](https://user-images.githubusercontent.com/11347342/97238813-9258a080-17ea-11eb-9a85-428645b64fe1.png)

**Comment by kishok** [comment]
Thanks @LeJeanbono. Is Angular testing utilities like **waitForAsync** can't we use inside the mocha statements for asynchronous tests?

**Comment by LeJeanbono** [comment]
Try to use it in a normal angular test (no cypress context).
