### ISSUE TITLE
Cypress Dashboard

### ISSUE THREAD

**Issue by LeJeanbono** [bahmutov/cypress-angular-unit-test#187]
Link the lib on a Cypress Dashboard project

**Comment by bahmutov** [comment]
done, see the dashboard [![cypress-angular-unit-test](https://img.shields.io/endpoint?url=https://dashboard.cypress.io/badge/simple/nf7zag/master&style=flat&logo=cypress)](https://dashboard.cypress.io/projects/nf7zag/runs)
