### ISSUE TITLE
Combined Coverage Report For Unit + E2E testing

### ISSUE THREAD

**Issue by szai0103** [bahmutov/cypress-angular-unit-test#188]
Hi, all, I need to have this combined coverage report, so, please can guide me on how exactly is supposed to be done with Angular? 
Here is [my project](https://github.com/szai0103/angular-weather-app/tree/combined-coverage) where I tried out the example from here: [Combined End-to-end and Unit Test Coverage](https://glebbahmutov.com/blog/combined-end-to-end-and-unit-test-coverage/) and this the repo from tutorial: [demo-battery-api](https://github.com/bahmutov/demo-battery-api/tree/cover-unit-tests-3) .
But for some reason, it reset the coverage after executing the integration tests.

**Comment by szai0103** [comment]
Thanks a lot for the example, but please, can u give some instructions on how exactly need to run for collection both e2e and unit tests coverage?

**Comment by LeJeanbono** [comment]
`cypress run` will run both `integration` and `e2e` tests, then you can find the report at `coverage/lcov-report/index.html`

**Comment by szai0103** [comment]
thanks, I have already done this with my project and it worked perfectly the combination :)))
