### ISSUE TITLE
Testing Angular Service

### ISSUE THREAD

**Issue by szai0103** [bahmutov/cypress-angular-unit-test#189]
I have problems with creating unit tests for my AuthService properties and methods. I couldn`t find any example on the web. Please, can u provide an example?

**Comment by LeJeanbono** [comment]
Hi @szai0103 !
Can you give your AuthService and all related mecanism please ?

**Comment by szai0103** [comment]
`auth.service.ts`
import {Injectable} from "@angular/core";
import * as auth0 from "auth0-js";
import {Router} from "@angular/router";
import {User} from "./models/user.model";
import {AUTH_CONFIG} from "../../auth_variables";

(window as any).global = window;

@Injectable({
  providedIn: "root"
})
export class AuthService {

  constructor(private router: Router) {
    this.getAccessToken();
  }

  get userProfile(): User {
    return {
      picture: window.localStorage.getItem("user_picture"),
      name: window.localStorage.getItem("user_name"),
      email: window.localStorage.getItem("user_email"),
    };
  }

  get isLoggedIn(): boolean {
    // Check if current date is before token
    // expiration and user is signed in locally
    return Date.now() < JSON.parse(window.localStorage.getItem("expires_at"));
  }
  tokenRenewalTimeout: number;
  // Create Auth0 web auth instance
  auth0 = new auth0.WebAuth({
    clientID: AUTH_CONFIG.clientId,
    domain: AUTH_CONFIG.domain,
    responseType: "token",
    redirectUri: AUTH_CONFIG.redirect,
    scope: AUTH_CONFIG.scope
  });

  private setSessionToLocalStorage(authResult, profile) {
    // Save authentication data and update login status subject
    window.localStorage.setItem("user_picture", profile.picture);
    window.localStorage.setItem("user_name", profile.name);
    window.localStorage.setItem("user_email", profile.email);
    window.localStorage.setItem("access_token", authResult.accessToken);
    window.localStorage.setItem("expires_at", JSON.stringify(
      authResult.expiresIn * 1000 + new Date().getTime()
    ));

    // schedule a token renewal
    this.scheduleRenewal();
  }

  login() {
    // Auth0 authorize request
    try {
      this.auth0.authorize();
    } catch (e) {
      throw new Error("Not authorized!");
    }
  }

  handleLoginCallback() {
    // When Auth0 hash parsed, get profile
    this.auth0.parseHash((err, authResult) => {
      if (authResult && authResult.accessToken) {
        this.getUserInfo(authResult);
      } else if (err) {
        alert(`Error: ${err.error}. Check the console for further details.`);
      }
      this.router.navigate(["/"]);
    });
  }

  private getAccessToken() {
    if (window.localStorage.getItem("access_token") == null) {
      this.auth0.checkSession({}, (err, authResult) => {
        if (authResult && authResult.accessToken) {
          this.getUserInfo(authResult);
        } else {
          console.warn(`Could not get a token (${err.error}: ${err.error_description}).`);
          this.clearStoredData();
        }
      });
    }
  }

  scheduleRenewal() {
    const expiresAt = JSON.parse(localStorage.getItem("expires_at") || "");
    const delay = expiresAt - Date.now();
    if (delay > 0) {
      this.tokenRenewalTimeout = setTimeout(() => {
        this.getAccessToken();
      }, delay);
    }
  }

  getUserInfo(authResult) {
    // Use access token to retrieve user's profile and set session
    this.auth0.client.userInfo(authResult.accessToken, (err, profile) => {
      if (profile) {
        this.setSessionToLocalStorage(authResult, profile);
      }
    });

  }

  logout() {
    // Log out of Auth0 session
    this.auth0.logout({
      returnTo: AUTH_CONFIG.returnTo,
      clientID: AUTH_CONFIG.clientId
    });

    this.clearStoredData();
    clearTimeout(this.tokenRenewalTimeout);
  }

  clearStoredData() {
    window.localStorage.removeItem("access_token");
    window.localStorage.removeItem("expires_at");
    window.localStorage.removeItem("user_picture");
    window.localStorage.removeItem("user_name");
    window.localStorage.removeItem("user_email");
  }
}

**Comment by szai0103** [comment]
`import {Injectable} from "@angular/core";
import * as auth0 from "auth0-js";
import {Router} from "@angular/router";
import {User} from "./models/user.model";
import {AUTH_CONFIG} from "../../auth_variables";

(window as any).global = window;

@Injectable({
  providedIn: "root"
})
export class AuthService {

  constructor(private router: Router) {
    this.getAccessToken();
  }

  get userProfile(): User {
    return {
      picture: window.localStorage.getItem("user_picture"),
      name: window.localStorage.getItem("user_name"),
      email: window.localStorage.getItem("user_email"),
    };
  }

  get isLoggedIn(): boolean {
    // Check if current date is before token
    // expiration and user is signed in locally
    return Date.now() < JSON.parse(window.localStorage.getItem("expires_at"));
  }
  tokenRenewalTimeout: number;
  // Create Auth0 web auth instance
  auth0 = new auth0.WebAuth({
    clientID: AUTH_CONFIG.clientId,
    domain: AUTH_CONFIG.domain,
    responseType: "token",
    redirectUri: AUTH_CONFIG.redirect,
    scope: AUTH_CONFIG.scope
  });

  private setSessionToLocalStorage(authResult, profile) {
    // Save authentication data and update login status subject
    window.localStorage.setItem("user_picture", profile.picture);
    window.localStorage.setItem("user_name", profile.name);
    window.localStorage.setItem("user_email", profile.email);
    window.localStorage.setItem("access_token", authResult.accessToken);
    window.localStorage.setItem("expires_at", JSON.stringify(
      authResult.expiresIn * 1000 + new Date().getTime()
    ));

    // schedule a token renewal
    this.scheduleRenewal();
  }

  login() {
    // Auth0 authorize request
    try {
      this.auth0.authorize();
    } catch (e) {
      throw new Error("Not authorized!");
    }
  }

  handleLoginCallback() {
    // When Auth0 hash parsed, get profile
    this.auth0.parseHash((err, authResult) => {
      if (authResult && authResult.accessToken) {
        this.getUserInfo(authResult);
      } else if (err) {
        alert(`Error: ${err.error}. Check the console for further details.`);
      }
      this.router.navigate(["/"]);
    });
  }

  private getAccessToken() {
    if (window.localStorage.getItem("access_token") == null) {
      this.auth0.checkSession({}, (err, authResult) => {
        if (authResult && authResult.accessToken) {
          this.getUserInfo(authResult);
        } else {
          console.warn(`Could not get a token (${err.error}: ${err.error_description}).`);
          this.clearStoredData();
        }
      });
    }
  }

  scheduleRenewal() {
    const expiresAt = JSON.parse(localStorage.getItem("expires_at") || "");
    const delay = expiresAt - Date.now();
    if (delay > 0) {
      this.tokenRenewalTimeout = setTimeout(() => {
        this.getAccessToken();
      }, delay);
    }
  }

  getUserInfo(authResult) {
    // Use access token to retrieve user's profile and set session
    this.auth0.client.userInfo(authResult.accessToken, (err, profile) => {
      if (profile) {
        this.setSessionToLocalStorage(authResult, profile);
      }
    });

  }

  logout() {
    // Log out of Auth0 session
    this.auth0.logout({
      returnTo: AUTH_CONFIG.returnTo,
      clientID: AUTH_CONFIG.clientId
    });

    this.clearStoredData();
    clearTimeout(this.tokenRenewalTimeout);
  }

  clearStoredData() {
    window.localStorage.removeItem("access_token");
    window.localStorage.removeItem("expires_at");
    window.localStorage.removeItem("user_picture");
    window.localStorage.removeItem("user_name");
    window.localStorage.removeItem("user_email");
  }
}
`

**Comment by szai0103** [comment]
So that these methods are colored in red for not covered by e2e testing:


![Uploading Screenshot 2020-11-06 at 10.55.14.png…]()

**Comment by LeJeanbono** [comment]
A regular unit-test with TestBed can do that.
`cypress-angulat-unit-test` is used for rendering component.

**Comment by szai0103** [comment]
> A regular unit-test with TestBed can do that.
> `cypress-angulat-unit-test` is used for rendering component.

So, do u mean that I need karma for testing this service and it is now possible with cypress?

**Comment by kishok** [comment]
@szai0103 Basically karma and cypress are test runner, you can use whatever tool suits for test automation. Angular **TestBed** provides testing utilities for services, components ,pipes, etc. for angular apps. To use TestBed in cypress, need to do test-setup before running the test suites like below:

```
before(() => {
  // Init Angular stuff
  getTestBed().resetTestEnvironment();

  getTestBed().initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
  )

  getTestBed().configureTestingModule({
    imports:[ HttpClientModule,
    //If angular-in-memory-api used
    HttpClientInMemoryWebApiModule.forRoot(InMemoryStore, {passThruUnknownUrl: true,apiBase:'api/'})
    ],
    providers:[{ provide:AuthService,useClass:AuthService}]
  });

  authService = getTestBed().inject(AuthService);
});

describe('Unit Test the  AuthService',()=>{
         it('can User Authenticated',(done)=>{
                authService.validate(credentials).then((response)=>{
                      //TODO assertions
                     done();
                   });
           });
});
```

**Comment by LeJeanbono** [comment]
Thanks @kishok exactly what I mean !
