### ISSUE TITLE
Assets image test not working

### ISSUE THREAD

**Issue by azaeng04** [bahmutov/cypress-angular-unit-test#202]
Executing assets test not working

![Screenshot 2020-11-08 21:29:12](https://user-images.githubusercontent.com/13921692/98482348-75b86180-2209-11eb-9a30-6b7835487872.png)

**Comment by LeJeanbono** [comment]
I will improve documentation on how to run in dev mode

**Comment by LeJeanbono** [comment]
Done : https://github.com/bahmutov/cypress-angular-unit-test#development
Can you tell me if it's ok now @azaeng04 ?

**Comment by azaeng04** [comment]
Thanks after setting up that way it worked :)
