### ISSUE TITLE
Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by azaeng04** [bahmutov/cypress-angular-unit-test#221]
I followed your example for the SCSS styles I indicated that I was to use the `raw-loader` & `sass-loader` in the webpack.config.

But I receive the following error:

```
Expected 'styles' to be an array of strings.
Because this error occurred during a before each hook we are skipping the remaining tests in the current suite: Login
```

![issue](https://user-images.githubusercontent.com/13921692/99267247-5edac600-282c-11eb-8dd2-3a7b278915bf.png)

**Comment by LeJeanbono** [comment]
You should set `"raw-loader": "1.0.0"`

An other solution is to use an other loader for `ts`
```
{
        test: /\.ts$/,
        loader: '@ngtools/webpack',
},
```
