### ISSUE TITLE
Merge setConfig and init*

### ISSUE THREAD

**Issue by yjaaidi** [bahmutov/cypress-angular-unit-test#249]
## Issues with current behavior

`setConfig` is currently somewhat hidden.

## Suggestion

Adding config options to the `init*` functions could be more intuitive ; in addition to keeping `setConfig`.

```ts
initEnv(AppComponent, {styles: '...', imports: [...]});
```

**Comment by LeJeanbono** [comment]
Hi @yjaaidi !
I agree with that :)
