### ISSUE TITLE
The state of this repository?

### ISSUE THREAD

**Issue by kayvanbree** [bahmutov/cypress-angular-unit-test#3]
I would really like to try unit testing with Cypress for our Angular application, but I can't get this to work:

- According to the readme, the code in this repository still doesn't work. According to [this pull request](https://github.com/bahmutov/cypress-angular-unit-test/pull/2) it should work. 

- When I try to clone the repository I get a lot of TypeScript errors, so I can't see if it works: 

```
E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
�[tsl] ���ERROR���� in ����E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,47)��
��      TS1005: ';' expected.��

E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
�[tsl] ���ERROR���� in ����E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,90)��
��      TS1005: '(' expected.��

E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
�[tsl] ���ERROR���� in ����E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,104)��
��      TS1005: ']' expected.��

E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts
�[tsl] ���ERROR���� in ����E:\Projects\libraries\cypress-angular-unit-test\node_modules\@types\jasmine\index.d.ts(138,112)��
��      TS1005: ',' expected.��
```

- Unlike the other cypress-*-unit-test packages (like [Vue](https://github.com/bahmutov/cypress-vue-unit-test)), cypress-angular-unit-test does not have an NPM package. 

- The Angular version used here is 5. I don't know if this will create compatibility errors when using Angular 6 or 7.

- If it does work, the readme is seriously outdated. 

- I don't know if this repo is still being maintained. 

Does this actually work? What are all those TypeScript errors? I'd like to create a PR, but I don't know how to fix those errors.

**Comment by meDavid** [comment]
Update your typescript dependency to version 2.8+ to get rid of the jasmine typings errors.

**Comment by kayvanbree** [comment]
This does work. I tried creating a mount method, but I'm not sure I'm doing it correctly. I don't have the computer I worked on right now, but it was something like this:

```javascript
const mount = (module: Type<TestingModule>, component) => {
    const html = `
      <head>
        <meta charset="UTF-8">
      </head>
      <body>
        <app-root></app-root>
      </body>
    `;
    const document = (cy as any).state('document');
    document.write(html);
    document.close();

    cy.get('app-root').then(el$ => {
      platformBrowserDynamic()
        .bootstrapModule(module)
        .then(function (moduleRef) {
          moduleRef.instance.app.bootstrap(component, el$.get(0));
        });
    });
}

export class TestingModule {
  app: ApplicationRef;
  ngDoBootstrap(app: ApplicationRef) {
    this.app = app;
  }
```

With a spec file like this:

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  entryComponents: [AppComponent]
})
class AppModule extends TestingModule {}

/* eslint-env mocha */
/* global cy */
describe('AppComponent', () => {
  beforeEach(() => {
    mount(AppModule, AppComponent);
  });

  it('works', () => {
    cy.contains('Welcome to app').should('be.visible');
  });

  it('works again', () => {
    cy.contains('Welcome to app').should('be.visible');
  });
});
```

Again, I typed this in here, so it might not be correct. My solution was very much like this though. 

Would the mount method be enought to ship as an npm module? If we pass a module's type and a component's type we can probably even use the module to provide mock services etcetera. Should we be able to access the created component? When writing tests, should we use clicks and stuff, or should we just call methods like in normal unit tests?

@bahmutov could you take a look at this issue?

**Comment by kayvanbree** [comment]
I'm trying to get this to work in the form of a library. [I updated Angular and added a project](https://github.com/kayvanbree/cypress-angular-unit-test/tree/npm-package), containing a file for the TestingModule and a file for the mount function. I'm having problems with bootstrapping the module now. For now, I'm stuck with the following error: 

`Can't resolve all parameters for ApplicationModule: (?).`

Could anyone here (@bahmutov, @geocine, @meDavid) take a look at this?

**Comment by meDavid** [comment]
> 
> `Can't resolve all parameters for ApplicationModule: (?).`
> 

Usually an error you see when the injector cannot satisfy all dependencies. In this case because it couldn't find the type of the first dependency. Could be due to no type metadata available after transpiling. Try adding the reflection polyfill:


`import 'core-js/es7/reflect';`

**Comment by kayvanbree** [comment]
That import is already included in my polyfill.ts. Also, according to this [Angular Github issue](https://github.com/angular/angular-cli/issues/12652), polyfills can't be added to a library. That would mean that everybody using this library would have to manually include the polyfill.

I haven't had any time at work and energy at home to work on this, also I really don't have the knowledge to fix the problems. Cypress runs on Electron, right? Could it be that this polyfill doesn't work for Electron, because its not actually an 'evergreen' browser?

**Comment by kayvanbree** [comment]
They changed something regarding that polyfill in Angular 7. Maybe this change could have something to do with my problem?

```
Continuing our focus on performance, we analyzed common mistakes across the ecosystem. We discovered that many developers were including the reflect-metadata polyfill in production, which is only needed in development.

To fix this, part of the update to v7 will automatically remove this from your polyfills.ts file, and then include it as a build step when building your application in JIT mode, removing this polyfill from production builds by default.
```

**Comment by meDavid** [comment]
@kayvanbree I wrote a blog post about it: https://medium.com/joolsoftware/unittesting-angular-components-with-cypress-202a38d9f81a

**Comment by kayvanbree** [comment]
I'm gonna give up. I'm still getting that error and when I clone your repo I get other errors again. I'll just keep using shitty the Karma runner, well, any time it actually wants to start...
