### ISSUE TITLE
Requires the ability to load the entire component module.

### ISSUE THREAD

**Issue by glagius** [bahmutov/cypress-angular-unit-test#366]
I tried writing a unit test for a simple component that uses Modules from Material Design and custom directives. As a result, I ran into the problem that I have to import the directive (otherwise, the component initialization fails with an error), but another error occurs.
It would be much easier if the documentation showed examples of testing complex components, or at least links to the main "possible" problems.

![spec-without-declaration](https://user-images.githubusercontent.com/36798811/110411031-69131f80-80bc-11eb-8876-905b19cbbfd2.png)
![spec-without-declaration-error](https://user-images.githubusercontent.com/36798811/110411064-7c25ef80-80bc-11eb-9bdc-489babfc2087.png)

**Comment by glagius** [comment]
I figured out the problem of modules, but the principle of loading all "dependent" modules is not completely clear. It would be cool if you could load a module instead of a component right away.

**Comment by LeJeanbono** [comment]
Hi @glagius ! Thank for your feedback !
I made some test, something like 
```ts
initEnvWithModule(AppModule); // where AppModule is your module application 
mount(FilterComponent);
```
If you provide me a reproductible project, I could validate it and make a release with it

**Comment by glagius** [comment]
Most likely, I do not have enough knowledge on isolated component testing. As soon as a component becomes a little more complex than a button with its own styles, the question arises how the module of this component should look like. Now in the project on which I checked the unit tests of cypress, all directives / pipes / third-party dependencies are in the Shared module, and are not directly imported into the component module.
I cannot initialize the entire Shared module (swears at the creation of two modules Shared and DinamycTests).
It turns out that for "composite" components that can inject services / directives / pipes, I need to initialize the entire application module at once?
Thank you for helping with such questions, and I really hope that I can normally drag a cypress for autotesting to our projects.

**Comment by glagius** [comment]
Guys tell me, is the description of the module settings up-to-date?
In your repository, the settings for the cypress plugin files are slightly different from what is indicated in the readme. More added helpers for the webpack preprocessor.
For testing purposes, I created a small application to test unit tests. https://github.com/glagius/contact-book
True, the component is not yet stupidly mounted due to an error with the paths.
If it's not difficult, can you see what the problem is?
