### ISSUE TITLE
Is there a way to load both AngularJs component/services and Angular in Cypress

### ISSUE THREAD

**Issue by Sathish787** [bahmutov/cypress-angular-unit-test#401]
I am evaluating Cypress tool to use it for Angular Unit testing. Our application is hybrid of AngularJs and Angular currently and progressing towards transforming everything to Angular. But, it is mix of AngularJs and Angular rightnow. 
I am trying to write cypress unit tests for components which imports services from AngularJS. I thought as testing component is Angular wouldn't cause any problem but when ran the test, it displays AngularJs is not loaded.
Attached screenshot for reference. Please direct me on this.
<img width="367" alt="angularjsloadissue" src="https://user-images.githubusercontent.com/22374311/114056622-db178980-985f-11eb-9a24-fb0c4bcb954f.png">

**Comment by LeJeanbono** [comment]
Hi @Sathish787 !
Did you tried to call `setAngularJSGlobal` before your test ?

```ts
import * as angular from 'angular';
import { setAngularJSGlobal } from '@angular/upgrade/static';

setAngularJSGlobal(angular);
```

If it don't work, can you give me a minimal reproducting repo to make some tests

**Comment by Sathish787** [comment]
Thanks LeJeanbono. I tried setAngularJSGlobal(angular). It didn't work. 

We made AngularJS components and services as npm package to the project and import it to the component.

**Comment by LeJeanbono** [comment]
A reproductible repository could really help on this, @Sathish787

**Comment by Sathish787** [comment]
Adding import statement in support.js solved the problem

import angular from 'angular';
