### ISSUE TITLE
Any plans to configure this angular project with new Cypress Component Test Runner

### ISSUE THREAD

**Issue by Sathish787** [bahmutov/cypress-angular-unit-test#406]
Any updates for Angular component testing using new Cypress Component Test Runner.

Thanks 
Sathish

**Comment by azaeng04** [comment]
There is an issue I logged on Cypress: https://github.com/cypress-io/cypress/issues/15903

**Comment by LeJeanbono** [comment]
I'm working on it !

**Comment by BrkCoder** [comment]
@LeJeanbono Hey thanks for the hard work, any update regarding this issue?

**Comment by LeJeanbono** [comment]
Merge will come this week !
Need to add some documentation (migration guide)

**Comment by BrkCoder** [comment]
@LeJeanbono thank you so much!!!

**Comment by Sathish787** [comment]
Any updates on setting up angular project with new cypress component test runner

**Comment by lmiller1990** [comment]
We are working on this. Will make an announcement when something is publicly available - WIP branch is currently here: https://github.com/bahmutov/cypress-angular-unit-test/pull/412

**Comment by LeJeanbono** [comment]
Released
