### ISSUE TITLE
Cant execute HTTPClient request with TDD

### ISSUE THREAD

**Issue by ashishpCACTUS** [bahmutov/cypress-angular-unit-test#429]
I am struggling to get the HTTPClient requests from a service and even from a Component call. 

Below is my Test file for a service call. 

```
import {  HttpClientModule, HttpClient, HttpHandler  } from '@angular/common/http';
import { getTestBed  } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';
import { SPOperationService } from './spoperation.service';

describe('SPOperationService', () => {

  let service: SPOperationService;
  before(() => {
    getTestBed().resetTestEnvironment();
    getTestBed().initTestEnvironment(
      BrowserDynamicTestingModule,
      platformBrowserDynamicTesting(),
    );
    getTestBed().configureTestingModule({
      providers: [SPOperationService, HttpClientModule, HttpClient, HttpHandler]
    });

    service = getTestBed().inject(SPOperationService);
  });

  it('Check service values', () => {
    const res = service.setBaseUrl("http://localhost:8080/sites/Medcomqa"); //// Sets the call to see if the 
    service.getUserInfo(103).then(res1 =>{ console.log(res1);});

    service.getUsers().then(res2=>{console.log(res2);});
    expect(1).equals(1);
  });

});
```

-----------------------------------------------------------------------------------------

Definitions for the two function getUserInfo and getUsers. This is a partial definition of the whole TS 
```
import { HttpClient, HttpHeaders, HttpErrorResponse } from '@angular/common/http';
export class SPOperationService {

constructor(private httpClient: HttpClient) { }

  async getUserInfo(id: number) {
    const url = this.getUserURL(id);
    console.log(url); //// http://localhost:8080/sites/Medcomqa/_api/web/getUserById(103)?$expand=Groups
    const res = await this.httpClient.get(url,).toPromise().catch((err: HttpErrorResponse) => {
      const error = err.error;
      return error;
    });
    console.log(res); //// Returns undefined. 
    return this.parseRetSingle(res); //// This can be excepted as the above result is undefined. 
  }

  async getUsers() {
    let result = await this.httpClient.get('https://jsonplaceholder.cypress.io/users?_limit=3',).toPromise().catch((err: HttpErrorResponse) => {
      const error = err.error;
      return error;
    });
    console.log("Await one" +  result); //// Returns undefined. 
    return result;
  }

}
```

I tried my own run and even the example code but both doesn't create any actual HTTP call. I don't receive any error in the catch but just an undefined value when I log after the call. 
-------------------------------------------------------------------------------------------------------------------------------------

I updated the code of the sample to see if there is any issue with my code but the example code creates a HTTP call.

Network component.ts 
```
import { Component, OnInit } from '@angular/core';
import { NetworkService } from '../network.service';

@Component({
  selector: 'app-network',
  templateUrl: './network.component.html',
  styleUrls: ['./network.component.css'],
})
export class NetworkComponent implements OnInit {
  users = [];

  constructor(private networkService: NetworkService) {}

  async ngOnInit(): Promise<void> {
    let res = await this.networkService.getUsers();
    console.log(res);
    this.users = res;
      //.subscribe((response) => (this.users = response));
  }
}
```

Network service.ts
```
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';

@Injectable({ providedIn: 'root' })
export class NetworkService {
  constructor(private httpClient: HttpClient) {}

  async getUsers() {
    // return this.httpClient.get<any[]>(
    //   'https://jsonplaceholder.cypress.io/users?_limit=3',
    // );

    let result = await this.httpClient.get('http://localhost:8080/sites/Medcomqa/_api/web/getUserById(103)?$expand=Groups',)
    .toPromise().catch((err: HttpErrorResponse) => {
      const error = err.error;
      return error;
    });

    return result; //// Provides me with result on the sample solution but not in my solution. 
  }
}
```

-------------------------------------------------------------------------------------------------------------------------------------------

I compared both the sample solution and my solution and could only find two difference 

1.  The Angular version. I am using 11.0.0 while the sample solution is using 11.2.11 so in the sample .ToPromise() comes deprecated while it doesn't provides me with that issue. 
2.  My Angular solution is configured to serve with a proxy settings to redirect calls to port 8080 on local environment. For this reason in my testbed I added a call to set the URL to 8080 for all my HTTPClient calls but it didn't worked. 

node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --proxy-config proxy.conf.json

proxy.conf.json
```json
{
  "/sites/*": {
      "target": "http://localhost:8080",
      "secure": false,
      "changeOrigin": true,
      "logLevel": "debug",
      "pathRewrite": {"^/sites" : "http://localhost:8080/sites"}
    }
}
```

I cant upgrade to 11.2.11 now as it started giving me some issues. Is there any other configurations I need to make for the HTTP calls to work from TestBed. I will be happy to provide the whole solution also if there is an need to the same.

**Comment by LeJeanbono** [comment]
You can find an example here : https://github.com/bahmutov/cypress-angular-unit-test/blob/master/src/app/network/network.component.cy-spec.ts
You can stub api response with `cy.intercept`
