### ISSUE TITLE
Is it possible to use cy.intercept in this framework as shown for react and vue application in new cypress component test runner 

### ISSUE THREAD

**Issue by Sathish787** [bahmutov/cypress-angular-unit-test#446]
Is it possible to use cy.intercept in this framework as shown for react and vue application in new cypress component test runner

**Comment by LeJeanbono** [comment]
Added an example here https://github.com/bahmutov/cypress-angular-unit-test/blob/master/src/app/network/network.component.cy-spec.ts

**Comment by LeJeanbono** [comment]
Are we ok @Sathish787 ?

**Comment by Sathish787** [comment]
Sorry, couldn't get time to work on this, stuck with other issue. I will update once I work on that.

Thanks @LeJeanbono

**Comment by Sathish787** [comment]
@LeJeanbono Thanks a lot. I could able to do cy.intercept and mock api data.
