### ISSUE TITLE
Is there a way to import module metadata of Angular component and not to repeat importing, declaring modules again in cypress spec file

### ISSUE THREAD

**Issue by Sathish787** [bahmutov/cypress-angular-unit-test#479]
Currently, It is kind of repeating things in cypress spec file that already done and available in component module file.

To write unit test, I have to import everything in spec file as below and could not re-use already declared and imported modules in Component.module.ts file

```typescript
beforeEach(() => {
    setConfig({ stylesheets: ["./cypress/support/styles/style.css"] });
    initEnv(GlobalConfigurationComponent, {
      declarations: [
        SchedulerComponent,
        ConfirmDialogComponent,
        SchedulerViewComponent,
      ],
      imports: [
        CommonModule,
        CardModule,
        ReactiveFormsModule,
        InputTextModule,
        ButtonModule,
        DropdownModule,
        RadioButtonModule,
        AccordionModule,
        ConstraintsModule,
        ExperimentalSettingsModule,
        RateLimitModule,
        EditSaveButtonModule,
        DialogModule,
        CalendarModule,
        OverlayPanelModule,
        CommentsChangelogSidebarModule,
        ConfirmDialogModule,
        BreadcrumbModule,
        HttpClientModule,
        LinkButtonModule,
        BrowserAnimationsModule,
        TranslateTestingModule.withTranslations("en", translation),
      ],
      providers: [
        GlobalConfigurationService,
        ConfigurationNotificationService,
        LoadingService,
        PermissionService,
        { provide: "$config", useValue: "/" },
      ],
    });   
  });
```
Need something kind of option to import from component module file. Like below:

```typescript
beforeEach(() => {
    setConfig({ stylesheets: ["./cypress/support/styles/style.css"] });
    initEnv(GlobalConfigurationComponent, {
      declarations: [
        GlobalConfigurationModule.declarations,        
      ],
      imports: [
        GlobalConfigurationModule.imports
        BrowserAnimationsModule,
        TranslateTestingModule.withTranslations("en", translation),
      ],
      providers: [
        GlobalConfigurationModule.providers,
        { provide: "$config", useValue: "/" },
      ],
    });   
  });
```

Please let me know if there are options to do this.

Thanks in Advance.

**Comment by LeJeanbono** [comment]
Something like this : https://github.com/bahmutov/cypress-angular-unit-test/blob/e1d1fe702bc6e56a2ffaac5ce14557b540c048a2/src/app/material-button/material-button.component.cy-spec.ts#L24 ?

**Comment by Sathish787** [comment]
> Something like this :
> 
> https://github.com/bahmutov/cypress-angular-unit-test/blob/e1d1fe702bc6e56a2ffaac5ce14557b540c048a2/src/app/material-button/material-button.component.cy-spec.ts#L24
> 
> ?

Not at app module level. Our app is splitted into multiple packages and will not have app.module.ts for all project except core app project. Looking  something at component module level.

Expectation: When use this - GlobalConfigurationModule.imports, it should fetch all imports from GlobalConfigurationModule or something similar if already exist.

**Comment by Sathish787** [comment]
@LeJeanbono Thanks a lot. It worked.

Correct syntax is:

```
initEnv({
   imports: [GlobalConfigurationModule]
})
```
then, mount component in tests:

```
it("", () => {
    mount(GlobalConfigurationComponent);
})
```

**Comment by LeJeanbono** [comment]
Yes, the component is now optional in `initEnv` method !
Happy testing !
