### ISSUE TITLE
Documentation: A test example on the way you test Stores.

### ISSUE THREAD

**Issue by azaeng04** [bahmutov/cypress-angular-unit-test#515]
Currently I don't see an example where you test Stores with Cypress. Would be much appreciated!

**Comment by LeJeanbono** [comment]
Do you want a specific store ?

**Comment by azaeng04** [comment]
Using actions, effects, reducers and selectors

**Comment by LeJeanbono** [comment]
Will use [ngrx](https://ngrx.io/), I think

**Comment by LeJeanbono** [comment]
Is it what you're looking for ? 
https://github.com/bahmutov/cypress-angular-unit-test/pull/516

**Comment by azaeng04** [comment]
Yes @LeJeanbono thanks that should be fine

**Comment by LeJeanbono** [comment]
You can also use mock with TestBed : https://ngrx.io/guide/store/testing#using-a-mock-store
